language: ruby

rvm:
  - 1.8.7

apt:
  packages:
    - dos2unix

gemfile:
  - $REDMINE_PATH/Gemfile

env:
  - REDMINE_VER=2.4.7

before_install:
  - export PLUGIN_NAME=computed_custom_field
  - export REDMINE_PATH=$HOME/redmine
  - git clone -b "$REDMINE_VER" --single-branch https://github.com/redmine/redmine.git $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database.yml.travis $REDMINE_PATH/config/database.yml
  - echo "gem 'nokogiri', '= 1.5.11'" >> $REDMINE_PATH/Gemfile
  - sed -ri 's/("selenium-webdriver")/\1, "= 2.40.0"/' $REDMINE_PATH/Gemfile
  - cd $REDMINE_PATH
  - echo "$(curl http://www.redmine.org/projects/redmine/repository/revisions/14891/diff/trunk/lib/tasks/redmine.rake?format=diff)" > redmine.rake.patch
  - dos2unix lib/tasks/redmine.rake
  - patch lib/tasks/redmine.rake redmine.rake.patch
  - echo "gem 'i18n', '0.6.11'" >> $REDMINE_PATH/Gemfile
  - echo "gem 'rack-cache', '1.2'" >> $REDMINE_PATH/Gemfile
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - phantomjs --webdriver 4444 &

install:
  - bundle install --without development

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME
  - bundle exec rake redmine:plugins:test:ui NAME=$PLUGIN_NAME

notifications:
  email: false
